package com.moko.support.mkgw4.entity;


import java.io.Serializable;

public enum ParamsKeyEnum implements Serializable {
    KEY_REBOOT(0x01),
    KEY_CLOSE(0x02),
    KEY_MANUFACTURER(0x05),
    KEY_CHIP_MAC(0x06),
    KEY_PCBA_STATUS(0x09),
    KEY_SELFTEST_STATUS(0x0A),
    KEY_RESET(0x0B),
    KEY_LED_INDICATOR(0x0C),
    KEY_NTP_SWITCH(0x0D),
    KEY_NTP_SYNC_INTERVAL(0x0E),
    KEY_NTP_SERVER(0x0F),
    KEY_TIME_ZONE(0x10),
    KEY_DEVICE_PAYLOAD_INTERVAL(0x11),
    KEY_DEVICE_STATUS_CHOOSE(0x12),
    KEY_POWER_LOSS_NOTIFY(0x13),
    KEY_PASSWORD(0x14),
    KEY_PASSWORD_VERIFY_ENABLE(0x15),
    KEY_LOW_POWER_NOTIFY_ENABLE(0x16),
    KEY_LOW_POWER_PERCENT(0x17),
    KEY_DELETE_BUFFER_DATA(0x18),
    KEY_AUTO_POWER_ON_ENABLE(0x19),



    /////MQTT参数
    KEY_MQTT_HOST(0x20),
    KEY_MQTT_PORT(0x21),
    KEY_MQTT_CLIENT_ID(0x22),
    KEY_MQTT_USERNAME(0x23),
    KEY_MQTT_PASSWORD(0x24),
    KEY_MQTT_CLEAN_SESSION(0x25),
    KEY_MQTT_KEEP_ALIVE(0x26),
    KEY_MQTT_QOS(0x27),
    KEY_SUBSCRIBE_TOPIC(0x28),
    KEY_PUBLISH_TOPIC(0x29),
    KEY_CONNECT_MODE(0x2A),
    KEY_MQTT_CA(0x2B),
    KEY_MQTT_CLIENT_CERT(0x2C),
    KEY_MQTT_CLIENT_KEY(0x2D),




    KEY_NETWORK_PRIORITY(0x30),
    KEY_APN(0x31),
    KEY_APN_NAME(0x32),
    KEY_APN_PASSWORD(0x33),
    KEY_CONNECT_NETWORK_TIMEOUT(0x34),



    KEY_SCAN_REPORT_MODE(0x40),
    KEY_SCAN_REPORT_ENABLE(0x41),
    KEY_REAL_SCAN_PERIODIC_REPORT_INTERVAL(0x42),
    KEY_PERIODIC_SCAN_IMMEDIATE_REPORT(0x43),
    KEY_PERIODIC_SCAN_PERIODIC_REPORT(0x44),
    KEY_UPLOAD_PRIORITY(0x45),
    KEY_DATA_RETENTION_PRIORITY(0x46),



    KEY_FILTER_RSSI(0x50),
    KEY_FILTER_PHY(0x51),
    KEY_FILTER_RELATIONSHIP(0x52),
    KEY_FILTER_MAC_PRECISE(0x53),
    KEY_FILTER_MAC_REVERSE(0x54),
    KEY_FILTER_MAC_RULES(0x55),
    KEY_FILTER_NAME_PRECISE(0x56),
    KEY_FILTER_NAME_REVERSE(0x57),
    KEY_FILTER_NAME_RULES(0x58),
    KEY_FILTER_RAW_DATA(0x59),
    KEY_FILTER_IBEACON_ENABLE(0x5A),
    KEY_FILTER_IBEACON_MAJOR_RANGE(0x5B),
    KEY_FILTER_IBEACON_MINOR_RANGE(0x5C),
    KEY_FILTER_IBEACON_UUID(0x5D),
    KEY_FILTER_EDDYSTONE_UID_ENABLE(0x5E),
    KEY_FILTER_EDDYSTONE_UID_NAMESPACE(0x5F),
    KEY_FILTER_EDDYSTONE_UID_INSTANCE(0x60),
    KEY_FILTER_EDDYSTONE_URL_ENABLE(0x61),
    KEY_FILTER_EDDYSTONE_URL(0x62),
    KEY_FILTER_EDDYSTONE_TLM_ENABLE(0x63),
    KEY_FILTER_EDDYSTONE_TLM_VERSION(0x64),
    KEY_FILTER_BXP_DEVICE(0x65),
    KEY_FILTER_BXP_ACC(0x66),
    KEY_FILTER_BXP_TH(0x67),
    KEY_FILTER_BXP_BUTTON_ENABLE(0x68),
    KEY_FILTER_BXP_BUTTON_RULES(0x69),
    KEY_FILTER_BXP_TAG_ENABLE(0x6A),
    // 精准过滤BXP-Tag开关
    KEY_FILTER_BXP_TAG_PRECISE(0x6B),
    // 反向过滤BXP-Tag开关
    KEY_FILTER_BXP_TAG_REVERSE(0x6C),
    // BXP-Tag过滤规则
    KEY_FILTER_BXP_TAG_RULES(0x6D),
    KEY_FILTER_MK_PIR_ENABLE(0x6E),
    KEY_FILTER_MK_PIR_DELAY_RES_STATUS(0x6F),
    KEY_FILTER_MK_PIR_DOOR_STATUS(0x70),
    KEY_FILTER_MK_PIR_SENSOR_SENSITIVITY(0x71),
    KEY_FILTER_MK_PIR_DETECTION_STATUS(0x72),
    KEY_FILTER_MK_PIR_MAJOR(0x73),
    KEY_FILTER_MK_PIR_MINOR(0x74),
    KEY_FILTER_MK_TOF_ENABLE(0x75),
    KEY_FILTER_MK_TOF_RULES(0x76),
    KEY_FILTER_OTHER_ENABLE(0x77),
    KEY_FILTER_OTHER_RELATIONSHIP(0x78),
    KEY_FILTER_OTHER_RULES(0x79),
    KEY_DUPLICATE_DATA_FILTER(0x7A),


    KEY_ADV_RESPONSE(0x80),
    KEY_ADV_NAME(0x81),
    KEY_IBEACON_MAJOR(0x82),
    KEY_IBEACON_MINOR(0x83),
    KEY_IBEACON_UUID(0x84),
    KEY_IBEACON_RSSI1M(0x85),
    KEY_ADV_INTERVAL(0x86),
    KEY_ADV_TX_POWER(0x87),
    KEY_ADV_TIMEOUT(0x88),




    KEY_FIX_MODE(0x90),
    KEY_PERIODIC_FIX_INTERVAL(0x91),
    KEY_ACC_WAKEUP_CONDITION(0x92),
    KEY_ACC_MOTION_CONDITION(0x93),
    KEY_MOTION_FIX_ENABLE_WHEN_START(0x94),
    KEY_MOTION_FIX_ENABLE_WHEN_TRIP(0x95),
    KEY_MOTION_FIX_INTERVAL_WHEN_TRIP(0x96),
    KEY_MOTION_FIX_TIMEOUT_WHEN_STOP(0x97),
    KEY_MOTION_FIX_ENABLE_WHEN_STOP(0x98),
    KEY_MOTION_FIX_ENABLE_WHEN_STATIONARY(0x99),
    KEY_MOTION_FIX_INTERVAL_WHEN_STATIONARY(0x9A),
    KEY_GPS_TIMEOUT(0x9B),
    KEY_GPS_PDOP(0x9C),




    KEY_IBEACON_PAYLOAD(0xA0),
    KEY_EDDYSTONE_UID_PAYLOAD(0xA1),
    KEY_EDDYSTONE_URL_PAYLOAD(0xA2),
    KEY_EDDYSTONE_TLM_PAYLOAD(0xA3),
    KEY_BXP_DEVICE_INFO_PAYLOAD(0xA4),
    KEY_BXP_ACC_PAYLOAD(0xA5),
    KEY_BXP_TH_PAYLOAD(0xA6),
    KEY_BXP_BUTTON_PAYLOAD(0xA7),
    KEY_BXP_TAG_PAYLOAD(0xA8),
    KEY_PIR_PAYLOAD(0xA9),
    KEY_TOF_PAYLOAD(0xAA),
    KEY_OTHER_PAYLOAD(0xAB),
    KEY_OTHER_PAYLOAD_DATA(0xAC),




    KEY_BATTERY_POWER(0xC0),
    KEY_IMEI(0xC1),
    KEY_ICC_ID(0xC2),
    KEY_NETWORK_STATUS(0xC4),
    KEY_MQTT_CONNECT_STATUS(0xC5),
    KEY_DEVICE_MODE(0xC7),
    ;

    private final int paramsKey;

    ParamsKeyEnum(int paramsKey) {
        this.paramsKey = paramsKey;
    }

    public int getParamsKey() {
        return paramsKey;
    }

    public static ParamsKeyEnum fromParamKey(int paramsKey) {
        for (ParamsKeyEnum paramsKeyEnum : ParamsKeyEnum.values()) {
            if (paramsKeyEnum.getParamsKey() == paramsKey) {
                return paramsKeyEnum;
            }
        }
        return null;
    }
}
